set(_CATKIN_CURRENT_PACKAGE "main_node_pkg")
set(main_node_pkg_VERSION "0.0.0")
set(main_node_pkg_MAINTAINER "michal <michal@todo.todo>")
set(main_node_pkg_PACKAGE_FORMAT "2")
set(main_node_pkg_BUILD_DEPENDS "roscpp")
set(main_node_pkg_BUILD_EXPORT_DEPENDS "roscpp")
set(main_node_pkg_BUILDTOOL_DEPENDS "catkin")
set(main_node_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(main_node_pkg_EXEC_DEPENDS "roscpp")
set(main_node_pkg_RUN_DEPENDS "roscpp")
set(main_node_pkg_TEST_DEPENDS )
set(main_node_pkg_DOC_DEPENDS )
set(main_node_pkg_URL_WEBSITE "")
set(main_node_pkg_URL_BUGTRACKER "")
set(main_node_pkg_URL_REPOSITORY "")
set(main_node_pkg_DEPRECATED "")