// Generated by gencpp from file custom_msg_pkg/ChangeNodeStateServiceMsg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESERVICEMSG_H
#define CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESERVICEMSG_H

#include <ros/service_traits.h>


#include <custom_msg_pkg/ChangeNodeStateServiceMsgRequest.h>
#include <custom_msg_pkg/ChangeNodeStateServiceMsgResponse.h>


namespace custom_msg_pkg
{

struct ChangeNodeStateServiceMsg
{

typedef ChangeNodeStateServiceMsgRequest Request;
typedef ChangeNodeStateServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeNodeStateServiceMsg
} // namespace custom_msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsg > {
  static const char* value()
  {
    return "e7cf3a237ea1ba28a266b276ffbdbbae";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateServiceMsg&) { return value(); }
};

template<>
struct DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsg > {
  static const char* value()
  {
    return "custom_msg_pkg/ChangeNodeStateServiceMsg";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsgRequest> should match 
// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsg > 
template<>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsgRequest> should match 
// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsg > 
template<>
struct DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsgResponse> should match 
// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsg > 
template<>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msg_pkg::ChangeNodeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsgResponse> should match 
// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsg > 
template<>
struct DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msg_pkg::ChangeNodeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESERVICEMSG_H
