// Generated by gencpp from file custom_msg_pkg/ChangeNodeStateSrv.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESRV_H
#define CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESRV_H

#include <ros/service_traits.h>


#include <custom_msg_pkg/ChangeNodeStateSrvRequest.h>
#include <custom_msg_pkg/ChangeNodeStateSrvResponse.h>


namespace custom_msg_pkg
{

struct ChangeNodeStateSrv
{

typedef ChangeNodeStateSrvRequest Request;
typedef ChangeNodeStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeNodeStateSrv
} // namespace custom_msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrv > {
  static const char* value()
  {
    return "e7cf3a237ea1ba28a266b276ffbdbbae";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrv&) { return value(); }
};

template<>
struct DataType< ::custom_msg_pkg::ChangeNodeStateSrv > {
  static const char* value()
  {
    return "custom_msg_pkg/ChangeNodeStateSrv";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrvRequest> should match 
// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrv > 
template<>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrv >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateSrvRequest> should match 
// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateSrv > 
template<>
struct DataType< ::custom_msg_pkg::ChangeNodeStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msg_pkg::ChangeNodeStateSrv >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrvResponse> should match 
// service_traits::MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrv > 
template<>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrv >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateSrvResponse> should match 
// service_traits::DataType< ::custom_msg_pkg::ChangeNodeStateSrv > 
template<>
struct DataType< ::custom_msg_pkg::ChangeNodeStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msg_pkg::ChangeNodeStateSrv >::value();
  }
  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESRV_H
