// Generated by gencpp from file custom_msg_pkg/SCNChangeStateServiceMsg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_SCNCHANGESTATESERVICEMSG_H
#define CUSTOM_MSG_PKG_MESSAGE_SCNCHANGESTATESERVICEMSG_H

#include <ros/service_traits.h>


#include <custom_msg_pkg/SCNChangeStateServiceMsgRequest.h>
#include <custom_msg_pkg/SCNChangeStateServiceMsgResponse.h>


namespace custom_msg_pkg
{

struct SCNChangeStateServiceMsg
{

typedef SCNChangeStateServiceMsgRequest Request;
typedef SCNChangeStateServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SCNChangeStateServiceMsg
} // namespace custom_msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsg > {
  static const char* value()
  {
    return "e7cf3a237ea1ba28a266b276ffbdbbae";
  }

  static const char* value(const ::custom_msg_pkg::SCNChangeStateServiceMsg&) { return value(); }
};

template<>
struct DataType< ::custom_msg_pkg::SCNChangeStateServiceMsg > {
  static const char* value()
  {
    return "custom_msg_pkg/SCNChangeStateServiceMsg";
  }

  static const char* value(const ::custom_msg_pkg::SCNChangeStateServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsgRequest> should match 
// service_traits::MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsg > 
template<>
struct MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::SCNChangeStateServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msg_pkg::SCNChangeStateServiceMsgRequest> should match 
// service_traits::DataType< ::custom_msg_pkg::SCNChangeStateServiceMsg > 
template<>
struct DataType< ::custom_msg_pkg::SCNChangeStateServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msg_pkg::SCNChangeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::SCNChangeStateServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsgResponse> should match 
// service_traits::MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsg > 
template<>
struct MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msg_pkg::SCNChangeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::SCNChangeStateServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msg_pkg::SCNChangeStateServiceMsgResponse> should match 
// service_traits::DataType< ::custom_msg_pkg::SCNChangeStateServiceMsg > 
template<>
struct DataType< ::custom_msg_pkg::SCNChangeStateServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msg_pkg::SCNChangeStateServiceMsg >::value();
  }
  static const char* value(const ::custom_msg_pkg::SCNChangeStateServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_SCNCHANGESTATESERVICEMSG_H
