set(_CATKIN_CURRENT_PACKAGE "servo_control_node_pkg")
set(servo_control_node_pkg_VERSION "0.0.0")
set(servo_control_node_pkg_MAINTAINER "mkt <mkt@celestial.pl>")
set(servo_control_node_pkg_PACKAGE_FORMAT "2")
set(servo_control_node_pkg_BUILD_DEPENDS "roscpp" "std_msgs" "custom_msg_pkg")
set(servo_control_node_pkg_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(servo_control_node_pkg_BUILDTOOL_DEPENDS "catkin")
set(servo_control_node_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(servo_control_node_pkg_EXEC_DEPENDS "roscpp" "std_msgs" "custom_msg_pkg")
set(servo_control_node_pkg_RUN_DEPENDS "roscpp" "std_msgs" "custom_msg_pkg")
set(servo_control_node_pkg_TEST_DEPENDS )
set(servo_control_node_pkg_DOC_DEPENDS )
set(servo_control_node_pkg_URL_WEBSITE "")
set(servo_control_node_pkg_URL_BUGTRACKER "")
set(servo_control_node_pkg_URL_REPOSITORY "")
set(servo_control_node_pkg_DEPRECATED "")