#pragma once

//----------------------------------------------------------------
//           DEFINITIONS
#ifdef _USE_TCP_PROTOCOL_
#define TCP_PORT_NO1		2001
#define TCP_PORT_NO2		2002
#endif // _USE_TCP_PROTOCOL_

#ifndef _USE_TCP_PROTOCOL_
#define UDP_PORT_NO1		3001
#define UDP_PORT_NO2		3002
#endif // _USE_TCP_PROTOCOL_

#define	PACKET_HEADER		0xAA

enum _PACKET_SENDOFFSET
{
	SENDOFFSET_HEADER = 0,
	SENDOFFSET_LENGTH,
	SENDOFFSET_SYNC,
	SENDOFFSET_AXIS,
	SENDOFFSET_CMD,
	SENDOFFSET_DATA,
};

enum _PACKET_RECVOFFSET
{
	RECVOFFSET_HEADER = 0,
	RECVOFFSET_LENGTH,
	RECVOFFSET_SYNC,
	RECVOFFSET_AXIS,
	RECVOFFSET_CMD,
	RECVOFFSET_STATUS,
	RECVOFFSET_DATA,
};

#define	MAX_BUFFER_SIZE			256
#define	MAX_SWINFO_LENGTH		250
