// Generated by gencpp from file custom_msg_pkg/ChangeNodeStateSrvRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESRVREQUEST_H
#define CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg_pkg
{
template <class ContainerAllocator>
struct ChangeNodeStateSrvRequest_
{
  typedef ChangeNodeStateSrvRequest_<ContainerAllocator> Type;

  ChangeNodeStateSrvRequest_()
    : targetState(0)
    , callerId(0)  {
    }
  ChangeNodeStateSrvRequest_(const ContainerAllocator& _alloc)
    : targetState(0)
    , callerId(0)  {
  (void)_alloc;
    }



   typedef int32_t _targetState_type;
  _targetState_type targetState;

   typedef int32_t _callerId_type;
  _callerId_type callerId;





  typedef boost::shared_ptr< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeNodeStateSrvRequest_

typedef ::custom_msg_pkg::ChangeNodeStateSrvRequest_<std::allocator<void> > ChangeNodeStateSrvRequest;

typedef boost::shared_ptr< ::custom_msg_pkg::ChangeNodeStateSrvRequest > ChangeNodeStateSrvRequestPtr;
typedef boost::shared_ptr< ::custom_msg_pkg::ChangeNodeStateSrvRequest const> ChangeNodeStateSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msg_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'custom_msg_pkg': ['/home/michal/catkin_ws/src/custom_msg_pkg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab4ca4991a5634318e6eeaa0eb1a11c8";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab4ca4991a563431ULL;
  static const uint64_t static_value2 = 0x8e6eeaa0eb1a11c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_pkg/ChangeNodeStateSrvRequest";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 targetState\n\
int32 callerId\n\
";
  }

  static const char* value(const ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targetState);
      stream.next(m.callerId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeNodeStateSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_pkg::ChangeNodeStateSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "targetState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.targetState);
    s << indent << "callerId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.callerId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_CHANGENODESTATESRVREQUEST_H
