// Generated by gencpp from file custom_msg_pkg/EziServosData.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_EZISERVOSDATA_H
#define CUSTOM_MSG_PKG_MESSAGE_EZISERVOSDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msg_pkg/EziServoData.h>

namespace custom_msg_pkg
{
template <class ContainerAllocator>
struct EziServosData_
{
  typedef EziServosData_<ContainerAllocator> Type;

  EziServosData_()
    : eziServoData()  {
    }
  EziServosData_(const ContainerAllocator& _alloc)
    : eziServoData(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::custom_msg_pkg::EziServoData_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::custom_msg_pkg::EziServoData_<ContainerAllocator> >::other >  _eziServoData_type;
  _eziServoData_type eziServoData;





  typedef boost::shared_ptr< ::custom_msg_pkg::EziServosData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_pkg::EziServosData_<ContainerAllocator> const> ConstPtr;

}; // struct EziServosData_

typedef ::custom_msg_pkg::EziServosData_<std::allocator<void> > EziServosData;

typedef boost::shared_ptr< ::custom_msg_pkg::EziServosData > EziServosDataPtr;
typedef boost::shared_ptr< ::custom_msg_pkg::EziServosData const> EziServosDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_pkg::EziServosData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msg_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'custom_msg_pkg': ['/home/michal/catkin_ws/src/custom_msg_pkg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::EziServosData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::EziServosData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::EziServosData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1386091f448a56ae9b0d394c1619d91";
  }

  static const char* value(const ::custom_msg_pkg::EziServosData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1386091f448a56aULL;
  static const uint64_t static_value2 = 0xe9b0d394c1619d91ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_pkg/EziServosData";
  }

  static const char* value(const ::custom_msg_pkg::EziServosData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EziServoData[] eziServoData\n\
\n\
================================================================================\n\
MSG: custom_msg_pkg/EziServoData\n\
string ipAddress\n\
EziServoStatus status\n\
EziServoActualMotion actualMotion\n\
\n\
\n\
================================================================================\n\
MSG: custom_msg_pkg/EziServoStatus\n\
bool connected\n\
bool enabled\n\
bool alarm\n\
bool emergency\n\
bool stopping \n\
bool moving\n\
\n\
\n\
\n\
================================================================================\n\
MSG: custom_msg_pkg/EziServoActualMotion\n\
int32 position\n\
int32 velocity\n\
int8 direction\n\
int32 positionError\n\
\n\
";
  }

  static const char* value(const ::custom_msg_pkg::EziServosData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.eziServoData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EziServosData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_pkg::EziServosData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_pkg::EziServosData_<ContainerAllocator>& v)
  {
    s << indent << "eziServoData[]" << std::endl;
    for (size_t i = 0; i < v.eziServoData.size(); ++i)
    {
      s << indent << "  eziServoData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msg_pkg::EziServoData_<ContainerAllocator> >::stream(s, indent + "    ", v.eziServoData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_EZISERVOSDATA_H
