// Generated by gencpp from file custom_msg_pkg/EziServoStatus.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_EZISERVOSTATUS_H
#define CUSTOM_MSG_PKG_MESSAGE_EZISERVOSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg_pkg
{
template <class ContainerAllocator>
struct EziServoStatus_
{
  typedef EziServoStatus_<ContainerAllocator> Type;

  EziServoStatus_()
    : connected(false)
    , enabled(false)
    , alarm(false)
    , emergency(false)
    , stopping(false)
    , moving(false)  {
    }
  EziServoStatus_(const ContainerAllocator& _alloc)
    : connected(false)
    , enabled(false)
    , alarm(false)
    , emergency(false)
    , stopping(false)
    , moving(false)  {
  (void)_alloc;
    }



   typedef uint8_t _connected_type;
  _connected_type connected;

   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef uint8_t _alarm_type;
  _alarm_type alarm;

   typedef uint8_t _emergency_type;
  _emergency_type emergency;

   typedef uint8_t _stopping_type;
  _stopping_type stopping;

   typedef uint8_t _moving_type;
  _moving_type moving;





  typedef boost::shared_ptr< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> const> ConstPtr;

}; // struct EziServoStatus_

typedef ::custom_msg_pkg::EziServoStatus_<std::allocator<void> > EziServoStatus;

typedef boost::shared_ptr< ::custom_msg_pkg::EziServoStatus > EziServoStatusPtr;
typedef boost::shared_ptr< ::custom_msg_pkg::EziServoStatus const> EziServoStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msg_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'custom_msg_pkg': ['/home/michal/catkin_ws/src/custom_msg_pkg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f22805727de3ca4b7981acde30ca7355";
  }

  static const char* value(const ::custom_msg_pkg::EziServoStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf22805727de3ca4bULL;
  static const uint64_t static_value2 = 0x7981acde30ca7355ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_pkg/EziServoStatus";
  }

  static const char* value(const ::custom_msg_pkg::EziServoStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool connected\n\
bool enabled\n\
bool alarm\n\
bool emergency\n\
bool stopping \n\
bool moving\n\
\n\
\n\
";
  }

  static const char* value(const ::custom_msg_pkg::EziServoStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connected);
      stream.next(m.enabled);
      stream.next(m.alarm);
      stream.next(m.emergency);
      stream.next(m.stopping);
      stream.next(m.moving);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EziServoStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_pkg::EziServoStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_pkg::EziServoStatus_<ContainerAllocator>& v)
  {
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alarm);
    s << indent << "emergency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency);
    s << indent << "stopping: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stopping);
    s << indent << "moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moving);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_EZISERVOSTATUS_H
