(cl:defpackage custom_msg_pkg-srv
  (:use )
  (:export
   "CHANGENODESTATESERVICEMSG"
   "<CHANGENODESTATESERVICEMSG-REQUEST>"
   "CHANGENODESTATESERVICEMSG-REQUEST"
   "<CHANGENODESTATESERVICEMSG-RESPONSE>"
   "CHANGENODESTATESERVICEMSG-RESPONSE"
  ))

