(cl:defpackage custom_msg_pkg-srv
  (:use )
  (:export
   "SCNCHANGESTATESERVICEMSG"
   "<SCNCHANGESTATESERVICEMSG-REQUEST>"
   "SCNCHANGESTATESERVICEMSG-REQUEST"
   "<SCNCHANGESTATESERVICEMSG-RESPONSE>"
   "SCNCHANGESTATESERVICEMSG-RESPONSE"
  ))

