(cl:defpackage custom_msg_pkg-srv
  (:use )
  (:export
   "CHANGENODESTATESRV"
   "<CHANGENODESTATESRV-REQUEST>"
   "CHANGENODESTATESRV-REQUEST"
   "<CHANGENODESTATESRV-RESPONSE>"
   "CHANGENODESTATESRV-RESPONSE"
  ))

